name: cpr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.0=h8c45485_0
  - bottleneck=1.3.5=py39h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - cffi=1.15.1=py39h74dc2b5_0
  - cfitsio=3.470=hf0d0db6_6
  - charls=2.2.0=h2531618_0
  - charset-normalizer=2.1.0=pyhd8ed1ab_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - comm=0.1.2=py39h06a4308_0
  - cryptography=37.0.4=py39hd97740a_0
  - cudatoolkit=11.6.0=hecad31d_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.11.0=py39h27cfd23_0
  - dask-core=2022.7.0=py39h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - entrypoints=0.4=py39h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - fsspec=2022.3.0=py39h06a4308_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2021.8.26=py39h4cda21f_0
  - imageio=2.19.3=py39h06a4308_0
  - ipykernel=6.19.2=py39hb070fc8_0
  - ipython=8.10.0=py39h06a4308_0
  - jedi=0.18.1=py39h06a4308_1
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h166bdaf_2
  - jupyter_client=7.3.4=py39h06a4308_0
  - jupyter_core=5.3.0=py39h06a4308_0
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.4.2=py39h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h295c915_0
  - libaec=1.0.4=he6710b0_1
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcurl=7.84.0=h91b91d3_0
  - libdeflate=1.8=h7f8727e_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.17=h166bdaf_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libnsl=2.0.0=h7f98852_0
  - libpng=1.6.37=h753d276_4
  - libprotobuf=3.20.1=h4ff587b_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=h8f2d780_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.12=h166bdaf_2
  - libzopfli=1.0.3=he6710b0_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - locket=1.0.0=py39h06a4308_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib=3.5.1=py39h06a4308_1
  - matplotlib-base=3.5.1=py39ha18d171_1
  - matplotlib-inline=0.1.6=py39h06a4308_0
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=py39h06a4308_0
  - nettle=3.6=he412f7d_0
  - networkx=2.8.4=py39h06a4308_0
  - numexpr=2.8.3=py39h807cd23_0
  - numpy-base=1.21.5=py39ha15fc14_3
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.3=py39h6a678d5_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py39hace64e9_1
  - pip=22.2.2=pyhd8ed1ab_0
  - platformdirs=2.5.2=py39h06a4308_0
  - prompt-toolkit=3.0.36=py39h06a4308_0
  - psutil=5.9.0=py39h5eee18b_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pysocks=1.7.1=py39hf3d152e_5
  - python=3.9.12=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytz=2022.1=py39h06a4308_0
  - pywavelets=1.3.0=py39h7f8727e_0
  - pyyaml=6.0=py39h7f8727e_1
  - pyzmq=23.2.0=py39h6a678d5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_0
  - scikit-image=0.19.2=py39h51133e4_0
  - scikit-learn=1.1.1=py39h6a678d5_0
  - setuptools=64.0.3=py39hf3d152e_0
  - sip=4.19.13=py39h295c915_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=h295c915_0
  - sqlite=3.39.2=h4ff8645_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.5.0=h924138e_1
  - tensorboardx=2.2=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tk=8.6.12=h27826a3_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.64.0=py39h06a4308_0
  - traitlets=5.7.1=py39h06a4308_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022b=h191b570_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zlib=1.2.12=h166bdaf_2
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.2.0
    - argparse==1.4.0
    - batchgenerators==0.25
    - cachetools==5.2.0
    - cleanlab==1.0
    - filelock==3.10.7
    - ftfy==6.1.1
    - future==0.18.3
    - google-auth==2.10.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.47.0
    - huggingface-hub==0.13.3
    - importlib-metadata==4.12.0
    - lime==0.2.0.1
    - linecache2==1.0.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - medpy==0.4.0
    - numpy==1.22.4
    - oauthlib==3.2.0
    - opencv-python==4.6.0.66
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.9.3
    - simpleitk==2.0.2
    - tb-nightly==2.11.0a20220814
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tokenizers==0.13.2
    - traceback2==1.4.0
    - transformers==4.27.4
    - unittest2==1.1.0
    - werkzeug==2.2.2
    - zipp==3.8.1
